let object = [
  {
    id: 1,
    name: "Editorial",
    isSelected: true,
    title: "Unsplash",
    text: "The internet’s source of freely-usable images. Powered by creators everywhere.",
  },
  {
    id: 2,
    name: "Following",
    isSelected: false,
    title: "Following",
    text: "The latest photos from photographers you follow.",
  },
  {
    id: 3,
    name: "Current Events",
    isSelected: false,
    title: "Current Events",
    text: "Covering the latest important events, news-worthy moments and movements from around the world — from political protests to cultural celebrations. When submitting, please provide a photo description so we understand the full context of the image.",
  },
  {
    id: 4,
    name: "3D Renders",
    isSelected: false,
    title: "3D Renders",
    text: "For the first time ever, Unsplash is accepting a new category of images outside of photography. Submit your 3-dimensional images, designed in the software of your choice, rendered into JPEG images.",
  },
  {
    id: 5,
    name: "Textures & Patterns",
    isSelected: false,
    title: "Textures & Patterns",
    text: "Whether you’re looking for stunning macro-photography or shots of complex architectural shapes — you’ve come to the right place.",
  },
  {
    id: 6,
    name: "Experimental",
    isSelected: false,
    title: "Experimental",
    text: "Through the use of unlikely textures, intriguing subject matter, and new formats — photography has the power to challenge our perspectives and push creativity forward.",
  },
  {
    id: 7,
    name: "Architecture",
    isSelected: false,
    title: "Architecture",
    text: "Explore exteriors from around the world — from brutalist buildings to minimalist structures that will give you a new appreciation for the art of architecture.",
  },
  {
    id: 8,
    name: "Nature",
    isSelected: false,
    title: "Nature",
    text: "Let’s celebrate the magic of Mother Earth — with images of everything our planet has to offer, from stunning seascapes, starry skies, and everything in between.",
  },
  {
    id: 9,
    name: "Business & Work",
    isSelected: false,
    title: "Business & Work",
    text: "Reflecting the realities of the modern workplace in their many forms — from images of remote working and start-ups to shots of engineers and artists at work.",
  },
  {
    id: 10,
    name: "Fashion",
    isSelected: false,
    title: "Fashion",
    text: "From street-style shots to editorial photography — find the latest trends in beauty and fashion.",
  },
  {
    id: 11,
    name: "Film",
    isSelected: false,
    title: "Film",
    text: "Beautiful analog photography from the past and present day — featuring polaroids, black and white images, grainy portraits, and more.",
  },
  {
    id: 12,
    name: "Food & Drink",
    isSelected: false,
    title: "Food & Drink",
    text: "It’s time to indulge, and throw yourself into the world of culinary photography — with shots of elaborate dinner parties, decadent pastries and more.",
  },
  {
    id: 13,
    name: "Health & Wellness",
    isSelected: false,
    title: "Health & Wellness",
    text: "Celebrate a healthy mind, body and soul with photographs that showcase everything from new medical discoveries and alternative medicines, to healthy eating and meditation.",
  },
  {
    id: 14,
    name: "People",
    isSelected: false,
    title: "People",
    text: "Real people, captured. Photography has the power to reflect the world around us, give voice to individuals and groups within our communities — and most importantly — tell their story.",
  },
  {
    id: 15,
    name: "Interiors",
    isSelected: false,
    title: "Interiors",
    text: "Whether it’s a peaceful bedroom or a cluttered kitchen — photographs of our spaces tell the story of who we are.",
  },
  {
    id: 16,
    name: "Street Photography",
    isSelected: false,
    title: "Street Photography",
    text: "From early morning commutes to neon-tinted nights, our streets have become the fabric of our shared history. This category encompasses street photography in every form.",
  },
  {
    id: 17,
    name: "Travel",
    isSelected: false,
    title: "Travel",
    text: "Discover hidden wonders and inspiring destinations around the world from the comfort of your own home.",
  },
  {
    id: 18,
    name: "Animals",
    isSelected: false,
    title: "Animals",
    text: "Exotic wildlife, pet kittens — and everything in between. Uncover the beauty of the animal kingdom through your screen.",
  },
  {
    id: 19,
    name: "Spirituality",
    isSelected: false,
    title: "Spirituality",
    text: "Photography has the ability to examine life’s big questions, by exploring themes of love, loss, healing and human connection.",
  },
  {
    id: 20,
    name: "Arts & Culture",
    isSelected: false,
    title: "Arts & Culture",
    text: "Your daily dose of culture — with photography showcasing the best in art, music and literature from around the world.",
  },
  {
    id: 21,
    name: "History",
    isSelected: false,
    title: "History",
    text: "Powerful photographs from the past — exploring monumental moments throughout our shared history.",
  },
  {
    id: 22,
    name: "Athletics",
    isSelected: false,
    title: "Athletics",
    text: "Ready, set, snap. Capturing action in the every day — from the tough gym workouts to the tense basketball games out on the court.",
  },
];

export default object;
